// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: DefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					SqlserverBatchRequestRate: SqlserverBatchRequestRateConfig{
						Enabled: true,
					},
					SqlserverBatchSQLCompilationRate: SqlserverBatchSQLCompilationRateConfig{
						Enabled: true,
					},
					SqlserverBatchSQLRecompilationRate: SqlserverBatchSQLRecompilationRateConfig{
						Enabled: true,
					},
					SqlserverComputerUptime: SqlserverComputerUptimeConfig{
						Enabled: true,
					},
					SqlserverCPUCount: SqlserverCPUCountConfig{
						Enabled: true,
					},
					SqlserverDatabaseBackupOrRestoreRate: SqlserverDatabaseBackupOrRestoreRateConfig{
						Enabled: true,
					},
					SqlserverDatabaseCount: SqlserverDatabaseCountConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SqlserverDatabaseCountAttributeKey{SqlserverDatabaseCountAttributeKeyDatabaseStatus},
					},
					SqlserverDatabaseExecutionErrors: SqlserverDatabaseExecutionErrorsConfig{
						Enabled: true,
					},
					SqlserverDatabaseFullScanRate: SqlserverDatabaseFullScanRateConfig{
						Enabled: true,
					},
					SqlserverDatabaseIo: SqlserverDatabaseIoConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SqlserverDatabaseIoAttributeKey{SqlserverDatabaseIoAttributeKeyPhysicalFilename, SqlserverDatabaseIoAttributeKeyLogicalFilename, SqlserverDatabaseIoAttributeKeyFileType, SqlserverDatabaseIoAttributeKeyDirection},
					},
					SqlserverDatabaseLatency: SqlserverDatabaseLatencyConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SqlserverDatabaseLatencyAttributeKey{SqlserverDatabaseLatencyAttributeKeyPhysicalFilename, SqlserverDatabaseLatencyAttributeKeyLogicalFilename, SqlserverDatabaseLatencyAttributeKeyFileType, SqlserverDatabaseLatencyAttributeKeyDirection},
					},
					SqlserverDatabaseOperations: SqlserverDatabaseOperationsConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SqlserverDatabaseOperationsAttributeKey{SqlserverDatabaseOperationsAttributeKeyPhysicalFilename, SqlserverDatabaseOperationsAttributeKeyLogicalFilename, SqlserverDatabaseOperationsAttributeKeyFileType, SqlserverDatabaseOperationsAttributeKeyDirection},
					},
					SqlserverDatabaseTempdbSpace: SqlserverDatabaseTempdbSpaceConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SqlserverDatabaseTempdbSpaceAttributeKey{SqlserverDatabaseTempdbSpaceAttributeKeyTempdbState},
					},
					SqlserverDatabaseTempdbVersionStoreSize: SqlserverDatabaseTempdbVersionStoreSizeConfig{
						Enabled: true,
					},
					SqlserverDeadlockRate: SqlserverDeadlockRateConfig{
						Enabled: true,
					},
					SqlserverIndexSearchRate: SqlserverIndexSearchRateConfig{
						Enabled: true,
					},
					SqlserverLockTimeoutRate: SqlserverLockTimeoutRateConfig{
						Enabled: true,
					},
					SqlserverLockWaitCount: SqlserverLockWaitCountConfig{
						Enabled: true,
					},
					SqlserverLockWaitRate: SqlserverLockWaitRateConfig{
						Enabled: true,
					},
					SqlserverLockWaitTimeAvg: SqlserverLockWaitTimeAvgConfig{
						Enabled: true,
					},
					SqlserverLoginRate: SqlserverLoginRateConfig{
						Enabled: true,
					},
					SqlserverLogoutRate: SqlserverLogoutRateConfig{
						Enabled: true,
					},
					SqlserverMemoryGrantsPendingCount: SqlserverMemoryGrantsPendingCountConfig{
						Enabled: true,
					},
					SqlserverMemoryUsage: SqlserverMemoryUsageConfig{
						Enabled: true,
					},
					SqlserverOsWaitDuration: SqlserverOsWaitDurationConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SqlserverOsWaitDurationAttributeKey{SqlserverOsWaitDurationAttributeKeyWaitCategory, SqlserverOsWaitDurationAttributeKeyWaitType},
					},
					SqlserverPageBufferCacheFreeListStallsRate: SqlserverPageBufferCacheFreeListStallsRateConfig{
						Enabled: true,
					},
					SqlserverPageBufferCacheHitRatio: SqlserverPageBufferCacheHitRatioConfig{
						Enabled: true,
					},
					SqlserverPageCheckpointFlushRate: SqlserverPageCheckpointFlushRateConfig{
						Enabled: true,
					},
					SqlserverPageLazyWriteRate: SqlserverPageLazyWriteRateConfig{
						Enabled: true,
					},
					SqlserverPageLifeExpectancy: SqlserverPageLifeExpectancyConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SqlserverPageLifeExpectancyAttributeKey{SqlserverPageLifeExpectancyAttributeKeyPerformanceCounterObjectName},
					},
					SqlserverPageLookupRate: SqlserverPageLookupRateConfig{
						Enabled: true,
					},
					SqlserverPageOperationRate: SqlserverPageOperationRateConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SqlserverPageOperationRateAttributeKey{SqlserverPageOperationRateAttributeKeyPageOperations},
					},
					SqlserverPageSplitRate: SqlserverPageSplitRateConfig{
						Enabled: true,
					},
					SqlserverProcessesBlocked: SqlserverProcessesBlockedConfig{
						Enabled: true,
					},
					SqlserverReplicaDataRate: SqlserverReplicaDataRateConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SqlserverReplicaDataRateAttributeKey{SqlserverReplicaDataRateAttributeKeyReplicaDirection},
					},
					SqlserverResourcePoolDiskOperations: SqlserverResourcePoolDiskOperationsConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SqlserverResourcePoolDiskOperationsAttributeKey{SqlserverResourcePoolDiskOperationsAttributeKeyDirection},
					},
					SqlserverResourcePoolDiskThrottledReadRate: SqlserverResourcePoolDiskThrottledReadRateConfig{
						Enabled: true,
					},
					SqlserverResourcePoolDiskThrottledWriteRate: SqlserverResourcePoolDiskThrottledWriteRateConfig{
						Enabled: true,
					},
					SqlserverTableCount: SqlserverTableCountConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SqlserverTableCountAttributeKey{SqlserverTableCountAttributeKeyTableState, SqlserverTableCountAttributeKeyTableStatus},
					},
					SqlserverTransactionDelay: SqlserverTransactionDelayConfig{
						Enabled: true,
					},
					SqlserverTransactionMirrorWriteRate: SqlserverTransactionMirrorWriteRateConfig{
						Enabled: true,
					},
					SqlserverTransactionRate: SqlserverTransactionRateConfig{
						Enabled: true,
					},
					SqlserverTransactionWriteRate: SqlserverTransactionWriteRateConfig{
						Enabled: true,
					},
					SqlserverTransactionLogFlushDataRate: SqlserverTransactionLogFlushDataRateConfig{
						Enabled: true,
					},
					SqlserverTransactionLogFlushRate: SqlserverTransactionLogFlushRateConfig{
						Enabled: true,
					},
					SqlserverTransactionLogFlushWaitRate: SqlserverTransactionLogFlushWaitRateConfig{
						Enabled: true,
					},
					SqlserverTransactionLogGrowthCount: SqlserverTransactionLogGrowthCountConfig{
						Enabled: true,
					},
					SqlserverTransactionLogShrinkCount: SqlserverTransactionLogShrinkCountConfig{
						Enabled: true,
					},
					SqlserverTransactionLogUsage: SqlserverTransactionLogUsageConfig{
						Enabled: true,
					},
					SqlserverUserConnectionCount: SqlserverUserConnectionCountConfig{
						Enabled: true,
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					HostName:              ResourceAttributeConfig{Enabled: true},
					ServerAddress:         ResourceAttributeConfig{Enabled: true},
					ServerPort:            ResourceAttributeConfig{Enabled: true},
					ServiceInstanceID:     ResourceAttributeConfig{Enabled: true},
					SqlserverComputerName: ResourceAttributeConfig{Enabled: true},
					SqlserverDatabaseName: ResourceAttributeConfig{Enabled: true},
					SqlserverInstanceName: ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					SqlserverBatchRequestRate: SqlserverBatchRequestRateConfig{
						Enabled: false,
					},
					SqlserverBatchSQLCompilationRate: SqlserverBatchSQLCompilationRateConfig{
						Enabled: false,
					},
					SqlserverBatchSQLRecompilationRate: SqlserverBatchSQLRecompilationRateConfig{
						Enabled: false,
					},
					SqlserverComputerUptime: SqlserverComputerUptimeConfig{
						Enabled: false,
					},
					SqlserverCPUCount: SqlserverCPUCountConfig{
						Enabled: false,
					},
					SqlserverDatabaseBackupOrRestoreRate: SqlserverDatabaseBackupOrRestoreRateConfig{
						Enabled: false,
					},
					SqlserverDatabaseCount: SqlserverDatabaseCountConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SqlserverDatabaseCountAttributeKey{SqlserverDatabaseCountAttributeKeyDatabaseStatus},
					},
					SqlserverDatabaseExecutionErrors: SqlserverDatabaseExecutionErrorsConfig{
						Enabled: false,
					},
					SqlserverDatabaseFullScanRate: SqlserverDatabaseFullScanRateConfig{
						Enabled: false,
					},
					SqlserverDatabaseIo: SqlserverDatabaseIoConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SqlserverDatabaseIoAttributeKey{SqlserverDatabaseIoAttributeKeyPhysicalFilename, SqlserverDatabaseIoAttributeKeyLogicalFilename, SqlserverDatabaseIoAttributeKeyFileType, SqlserverDatabaseIoAttributeKeyDirection},
					},
					SqlserverDatabaseLatency: SqlserverDatabaseLatencyConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SqlserverDatabaseLatencyAttributeKey{SqlserverDatabaseLatencyAttributeKeyPhysicalFilename, SqlserverDatabaseLatencyAttributeKeyLogicalFilename, SqlserverDatabaseLatencyAttributeKeyFileType, SqlserverDatabaseLatencyAttributeKeyDirection},
					},
					SqlserverDatabaseOperations: SqlserverDatabaseOperationsConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SqlserverDatabaseOperationsAttributeKey{SqlserverDatabaseOperationsAttributeKeyPhysicalFilename, SqlserverDatabaseOperationsAttributeKeyLogicalFilename, SqlserverDatabaseOperationsAttributeKeyFileType, SqlserverDatabaseOperationsAttributeKeyDirection},
					},
					SqlserverDatabaseTempdbSpace: SqlserverDatabaseTempdbSpaceConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SqlserverDatabaseTempdbSpaceAttributeKey{SqlserverDatabaseTempdbSpaceAttributeKeyTempdbState},
					},
					SqlserverDatabaseTempdbVersionStoreSize: SqlserverDatabaseTempdbVersionStoreSizeConfig{
						Enabled: false,
					},
					SqlserverDeadlockRate: SqlserverDeadlockRateConfig{
						Enabled: false,
					},
					SqlserverIndexSearchRate: SqlserverIndexSearchRateConfig{
						Enabled: false,
					},
					SqlserverLockTimeoutRate: SqlserverLockTimeoutRateConfig{
						Enabled: false,
					},
					SqlserverLockWaitCount: SqlserverLockWaitCountConfig{
						Enabled: false,
					},
					SqlserverLockWaitRate: SqlserverLockWaitRateConfig{
						Enabled: false,
					},
					SqlserverLockWaitTimeAvg: SqlserverLockWaitTimeAvgConfig{
						Enabled: false,
					},
					SqlserverLoginRate: SqlserverLoginRateConfig{
						Enabled: false,
					},
					SqlserverLogoutRate: SqlserverLogoutRateConfig{
						Enabled: false,
					},
					SqlserverMemoryGrantsPendingCount: SqlserverMemoryGrantsPendingCountConfig{
						Enabled: false,
					},
					SqlserverMemoryUsage: SqlserverMemoryUsageConfig{
						Enabled: false,
					},
					SqlserverOsWaitDuration: SqlserverOsWaitDurationConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SqlserverOsWaitDurationAttributeKey{SqlserverOsWaitDurationAttributeKeyWaitCategory, SqlserverOsWaitDurationAttributeKeyWaitType},
					},
					SqlserverPageBufferCacheFreeListStallsRate: SqlserverPageBufferCacheFreeListStallsRateConfig{
						Enabled: false,
					},
					SqlserverPageBufferCacheHitRatio: SqlserverPageBufferCacheHitRatioConfig{
						Enabled: false,
					},
					SqlserverPageCheckpointFlushRate: SqlserverPageCheckpointFlushRateConfig{
						Enabled: false,
					},
					SqlserverPageLazyWriteRate: SqlserverPageLazyWriteRateConfig{
						Enabled: false,
					},
					SqlserverPageLifeExpectancy: SqlserverPageLifeExpectancyConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SqlserverPageLifeExpectancyAttributeKey{SqlserverPageLifeExpectancyAttributeKeyPerformanceCounterObjectName},
					},
					SqlserverPageLookupRate: SqlserverPageLookupRateConfig{
						Enabled: false,
					},
					SqlserverPageOperationRate: SqlserverPageOperationRateConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SqlserverPageOperationRateAttributeKey{SqlserverPageOperationRateAttributeKeyPageOperations},
					},
					SqlserverPageSplitRate: SqlserverPageSplitRateConfig{
						Enabled: false,
					},
					SqlserverProcessesBlocked: SqlserverProcessesBlockedConfig{
						Enabled: false,
					},
					SqlserverReplicaDataRate: SqlserverReplicaDataRateConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SqlserverReplicaDataRateAttributeKey{SqlserverReplicaDataRateAttributeKeyReplicaDirection},
					},
					SqlserverResourcePoolDiskOperations: SqlserverResourcePoolDiskOperationsConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SqlserverResourcePoolDiskOperationsAttributeKey{SqlserverResourcePoolDiskOperationsAttributeKeyDirection},
					},
					SqlserverResourcePoolDiskThrottledReadRate: SqlserverResourcePoolDiskThrottledReadRateConfig{
						Enabled: false,
					},
					SqlserverResourcePoolDiskThrottledWriteRate: SqlserverResourcePoolDiskThrottledWriteRateConfig{
						Enabled: false,
					},
					SqlserverTableCount: SqlserverTableCountConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []SqlserverTableCountAttributeKey{SqlserverTableCountAttributeKeyTableState, SqlserverTableCountAttributeKeyTableStatus},
					},
					SqlserverTransactionDelay: SqlserverTransactionDelayConfig{
						Enabled: false,
					},
					SqlserverTransactionMirrorWriteRate: SqlserverTransactionMirrorWriteRateConfig{
						Enabled: false,
					},
					SqlserverTransactionRate: SqlserverTransactionRateConfig{
						Enabled: false,
					},
					SqlserverTransactionWriteRate: SqlserverTransactionWriteRateConfig{
						Enabled: false,
					},
					SqlserverTransactionLogFlushDataRate: SqlserverTransactionLogFlushDataRateConfig{
						Enabled: false,
					},
					SqlserverTransactionLogFlushRate: SqlserverTransactionLogFlushRateConfig{
						Enabled: false,
					},
					SqlserverTransactionLogFlushWaitRate: SqlserverTransactionLogFlushWaitRateConfig{
						Enabled: false,
					},
					SqlserverTransactionLogGrowthCount: SqlserverTransactionLogGrowthCountConfig{
						Enabled: false,
					},
					SqlserverTransactionLogShrinkCount: SqlserverTransactionLogShrinkCountConfig{
						Enabled: false,
					},
					SqlserverTransactionLogUsage: SqlserverTransactionLogUsageConfig{
						Enabled: false,
					},
					SqlserverUserConnectionCount: SqlserverUserConnectionCountConfig{
						Enabled: false,
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					HostName:              ResourceAttributeConfig{Enabled: false},
					ServerAddress:         ResourceAttributeConfig{Enabled: false},
					ServerPort:            ResourceAttributeConfig{Enabled: false},
					ServiceInstanceID:     ResourceAttributeConfig{Enabled: false},
					SqlserverComputerName: ResourceAttributeConfig{Enabled: false},
					SqlserverDatabaseName: ResourceAttributeConfig{Enabled: false},
					SqlserverInstanceName: ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(SqlserverBatchRequestRateConfig{}, SqlserverBatchSQLCompilationRateConfig{}, SqlserverBatchSQLRecompilationRateConfig{}, SqlserverComputerUptimeConfig{}, SqlserverCPUCountConfig{}, SqlserverDatabaseBackupOrRestoreRateConfig{}, SqlserverDatabaseCountConfig{}, SqlserverDatabaseExecutionErrorsConfig{}, SqlserverDatabaseFullScanRateConfig{}, SqlserverDatabaseIoConfig{}, SqlserverDatabaseLatencyConfig{}, SqlserverDatabaseOperationsConfig{}, SqlserverDatabaseTempdbSpaceConfig{}, SqlserverDatabaseTempdbVersionStoreSizeConfig{}, SqlserverDeadlockRateConfig{}, SqlserverIndexSearchRateConfig{}, SqlserverLockTimeoutRateConfig{}, SqlserverLockWaitCountConfig{}, SqlserverLockWaitRateConfig{}, SqlserverLockWaitTimeAvgConfig{}, SqlserverLoginRateConfig{}, SqlserverLogoutRateConfig{}, SqlserverMemoryGrantsPendingCountConfig{}, SqlserverMemoryUsageConfig{}, SqlserverOsWaitDurationConfig{}, SqlserverPageBufferCacheFreeListStallsRateConfig{}, SqlserverPageBufferCacheHitRatioConfig{}, SqlserverPageCheckpointFlushRateConfig{}, SqlserverPageLazyWriteRateConfig{}, SqlserverPageLifeExpectancyConfig{}, SqlserverPageLookupRateConfig{}, SqlserverPageOperationRateConfig{}, SqlserverPageSplitRateConfig{}, SqlserverProcessesBlockedConfig{}, SqlserverReplicaDataRateConfig{}, SqlserverResourcePoolDiskOperationsConfig{}, SqlserverResourcePoolDiskThrottledReadRateConfig{}, SqlserverResourcePoolDiskThrottledWriteRateConfig{}, SqlserverTableCountConfig{}, SqlserverTransactionDelayConfig{}, SqlserverTransactionMirrorWriteRateConfig{}, SqlserverTransactionRateConfig{}, SqlserverTransactionWriteRateConfig{}, SqlserverTransactionLogFlushDataRateConfig{}, SqlserverTransactionLogFlushRateConfig{}, SqlserverTransactionLogFlushWaitRateConfig{}, SqlserverTransactionLogGrowthCountConfig{}, SqlserverTransactionLogShrinkCountConfig{}, SqlserverTransactionLogUsageConfig{}, SqlserverUserConnectionCountConfig{}, ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := DefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}

func loadLogsBuilderConfig(t *testing.T, name string) LogsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := DefaultLogsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				HostName:              ResourceAttributeConfig{Enabled: true},
				ServerAddress:         ResourceAttributeConfig{Enabled: true},
				ServerPort:            ResourceAttributeConfig{Enabled: true},
				ServiceInstanceID:     ResourceAttributeConfig{Enabled: true},
				SqlserverComputerName: ResourceAttributeConfig{Enabled: true},
				SqlserverDatabaseName: ResourceAttributeConfig{Enabled: true},
				SqlserverInstanceName: ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				HostName:              ResourceAttributeConfig{Enabled: false},
				ServerAddress:         ResourceAttributeConfig{Enabled: false},
				ServerPort:            ResourceAttributeConfig{Enabled: false},
				ServiceInstanceID:     ResourceAttributeConfig{Enabled: false},
				SqlserverComputerName: ResourceAttributeConfig{Enabled: false},
				SqlserverDatabaseName: ResourceAttributeConfig{Enabled: false},
				SqlserverInstanceName: ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
