// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"fmt"

	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// SqlserverBatchRequestRateConfig provides config for the sqlserver.batch.request.rate metric.
type SqlserverBatchRequestRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverBatchRequestRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverBatchSQLCompilationRateConfig provides config for the sqlserver.batch.sql_compilation.rate metric.
type SqlserverBatchSQLCompilationRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverBatchSQLCompilationRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverBatchSQLRecompilationRateConfig provides config for the sqlserver.batch.sql_recompilation.rate metric.
type SqlserverBatchSQLRecompilationRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverBatchSQLRecompilationRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverComputerUptimeConfig provides config for the sqlserver.computer.uptime metric.
type SqlserverComputerUptimeConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverComputerUptimeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverCPUCountConfig provides config for the sqlserver.cpu.count metric.
type SqlserverCPUCountConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverCPUCountConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverDatabaseBackupOrRestoreRateConfig provides config for the sqlserver.database.backup_or_restore.rate metric.
type SqlserverDatabaseBackupOrRestoreRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverDatabaseBackupOrRestoreRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverDatabaseCountAttributeKey specifies the key of an attribute for the sqlserver.database.count metric.
type SqlserverDatabaseCountAttributeKey string

const (
	SqlserverDatabaseCountAttributeKeyDatabaseStatus SqlserverDatabaseCountAttributeKey = "database.status"
)

// SqlserverDatabaseCountConfig provides config for the sqlserver.database.count metric.
type SqlserverDatabaseCountConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                               `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SqlserverDatabaseCountAttributeKey `mapstructure:"attributes"`
}

func (ms *SqlserverDatabaseCountConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SqlserverDatabaseCountConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SqlserverDatabaseCountAttributeKeyDatabaseStatus:
		default:
			return fmt.Errorf("metric sqlserver.database.count doesn't have an attribute %v, valid attributes: [database.status]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SqlserverDatabaseExecutionErrorsConfig provides config for the sqlserver.database.execution.errors metric.
type SqlserverDatabaseExecutionErrorsConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverDatabaseExecutionErrorsConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverDatabaseFullScanRateConfig provides config for the sqlserver.database.full_scan.rate metric.
type SqlserverDatabaseFullScanRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverDatabaseFullScanRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverDatabaseIoAttributeKey specifies the key of an attribute for the sqlserver.database.io metric.
type SqlserverDatabaseIoAttributeKey string

const (
	SqlserverDatabaseIoAttributeKeyPhysicalFilename SqlserverDatabaseIoAttributeKey = "physical_filename"
	SqlserverDatabaseIoAttributeKeyLogicalFilename  SqlserverDatabaseIoAttributeKey = "logical_filename"
	SqlserverDatabaseIoAttributeKeyFileType         SqlserverDatabaseIoAttributeKey = "file_type"
	SqlserverDatabaseIoAttributeKeyDirection        SqlserverDatabaseIoAttributeKey = "direction"
)

// SqlserverDatabaseIoConfig provides config for the sqlserver.database.io metric.
type SqlserverDatabaseIoConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                            `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SqlserverDatabaseIoAttributeKey `mapstructure:"attributes"`
}

func (ms *SqlserverDatabaseIoConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SqlserverDatabaseIoConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SqlserverDatabaseIoAttributeKeyPhysicalFilename, SqlserverDatabaseIoAttributeKeyLogicalFilename, SqlserverDatabaseIoAttributeKeyFileType, SqlserverDatabaseIoAttributeKeyDirection:
		default:
			return fmt.Errorf("metric sqlserver.database.io doesn't have an attribute %v, valid attributes: [physical_filename, logical_filename, file_type, direction]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SqlserverDatabaseLatencyAttributeKey specifies the key of an attribute for the sqlserver.database.latency metric.
type SqlserverDatabaseLatencyAttributeKey string

const (
	SqlserverDatabaseLatencyAttributeKeyPhysicalFilename SqlserverDatabaseLatencyAttributeKey = "physical_filename"
	SqlserverDatabaseLatencyAttributeKeyLogicalFilename  SqlserverDatabaseLatencyAttributeKey = "logical_filename"
	SqlserverDatabaseLatencyAttributeKeyFileType         SqlserverDatabaseLatencyAttributeKey = "file_type"
	SqlserverDatabaseLatencyAttributeKeyDirection        SqlserverDatabaseLatencyAttributeKey = "direction"
)

// SqlserverDatabaseLatencyConfig provides config for the sqlserver.database.latency metric.
type SqlserverDatabaseLatencyConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                 `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SqlserverDatabaseLatencyAttributeKey `mapstructure:"attributes"`
}

func (ms *SqlserverDatabaseLatencyConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SqlserverDatabaseLatencyConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SqlserverDatabaseLatencyAttributeKeyPhysicalFilename, SqlserverDatabaseLatencyAttributeKeyLogicalFilename, SqlserverDatabaseLatencyAttributeKeyFileType, SqlserverDatabaseLatencyAttributeKeyDirection:
		default:
			return fmt.Errorf("metric sqlserver.database.latency doesn't have an attribute %v, valid attributes: [physical_filename, logical_filename, file_type, direction]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SqlserverDatabaseOperationsAttributeKey specifies the key of an attribute for the sqlserver.database.operations metric.
type SqlserverDatabaseOperationsAttributeKey string

const (
	SqlserverDatabaseOperationsAttributeKeyPhysicalFilename SqlserverDatabaseOperationsAttributeKey = "physical_filename"
	SqlserverDatabaseOperationsAttributeKeyLogicalFilename  SqlserverDatabaseOperationsAttributeKey = "logical_filename"
	SqlserverDatabaseOperationsAttributeKeyFileType         SqlserverDatabaseOperationsAttributeKey = "file_type"
	SqlserverDatabaseOperationsAttributeKeyDirection        SqlserverDatabaseOperationsAttributeKey = "direction"
)

// SqlserverDatabaseOperationsConfig provides config for the sqlserver.database.operations metric.
type SqlserverDatabaseOperationsConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                    `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SqlserverDatabaseOperationsAttributeKey `mapstructure:"attributes"`
}

func (ms *SqlserverDatabaseOperationsConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SqlserverDatabaseOperationsConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SqlserverDatabaseOperationsAttributeKeyPhysicalFilename, SqlserverDatabaseOperationsAttributeKeyLogicalFilename, SqlserverDatabaseOperationsAttributeKeyFileType, SqlserverDatabaseOperationsAttributeKeyDirection:
		default:
			return fmt.Errorf("metric sqlserver.database.operations doesn't have an attribute %v, valid attributes: [physical_filename, logical_filename, file_type, direction]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SqlserverDatabaseTempdbSpaceAttributeKey specifies the key of an attribute for the sqlserver.database.tempdb.space metric.
type SqlserverDatabaseTempdbSpaceAttributeKey string

const (
	SqlserverDatabaseTempdbSpaceAttributeKeyTempdbState SqlserverDatabaseTempdbSpaceAttributeKey = "tempdb.state"
)

// SqlserverDatabaseTempdbSpaceConfig provides config for the sqlserver.database.tempdb.space metric.
type SqlserverDatabaseTempdbSpaceConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                     `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SqlserverDatabaseTempdbSpaceAttributeKey `mapstructure:"attributes"`
}

func (ms *SqlserverDatabaseTempdbSpaceConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SqlserverDatabaseTempdbSpaceConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SqlserverDatabaseTempdbSpaceAttributeKeyTempdbState:
		default:
			return fmt.Errorf("metric sqlserver.database.tempdb.space doesn't have an attribute %v, valid attributes: [tempdb.state]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SqlserverDatabaseTempdbVersionStoreSizeConfig provides config for the sqlserver.database.tempdb.version_store.size metric.
type SqlserverDatabaseTempdbVersionStoreSizeConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverDatabaseTempdbVersionStoreSizeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverDeadlockRateConfig provides config for the sqlserver.deadlock.rate metric.
type SqlserverDeadlockRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverDeadlockRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverIndexSearchRateConfig provides config for the sqlserver.index.search.rate metric.
type SqlserverIndexSearchRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverIndexSearchRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverLockTimeoutRateConfig provides config for the sqlserver.lock.timeout.rate metric.
type SqlserverLockTimeoutRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverLockTimeoutRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverLockWaitCountConfig provides config for the sqlserver.lock.wait.count metric.
type SqlserverLockWaitCountConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverLockWaitCountConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverLockWaitRateConfig provides config for the sqlserver.lock.wait.rate metric.
type SqlserverLockWaitRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverLockWaitRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverLockWaitTimeAvgConfig provides config for the sqlserver.lock.wait_time.avg metric.
type SqlserverLockWaitTimeAvgConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverLockWaitTimeAvgConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverLoginRateConfig provides config for the sqlserver.login.rate metric.
type SqlserverLoginRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverLoginRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverLogoutRateConfig provides config for the sqlserver.logout.rate metric.
type SqlserverLogoutRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverLogoutRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverMemoryGrantsPendingCountConfig provides config for the sqlserver.memory.grants.pending.count metric.
type SqlserverMemoryGrantsPendingCountConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverMemoryGrantsPendingCountConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverMemoryUsageConfig provides config for the sqlserver.memory.usage metric.
type SqlserverMemoryUsageConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverMemoryUsageConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverOsWaitDurationAttributeKey specifies the key of an attribute for the sqlserver.os.wait.duration metric.
type SqlserverOsWaitDurationAttributeKey string

const (
	SqlserverOsWaitDurationAttributeKeyWaitCategory SqlserverOsWaitDurationAttributeKey = "wait.category"
	SqlserverOsWaitDurationAttributeKeyWaitType     SqlserverOsWaitDurationAttributeKey = "wait.type"
)

// SqlserverOsWaitDurationConfig provides config for the sqlserver.os.wait.duration metric.
type SqlserverOsWaitDurationConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SqlserverOsWaitDurationAttributeKey `mapstructure:"attributes"`
}

func (ms *SqlserverOsWaitDurationConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SqlserverOsWaitDurationConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SqlserverOsWaitDurationAttributeKeyWaitCategory, SqlserverOsWaitDurationAttributeKeyWaitType:
		default:
			return fmt.Errorf("metric sqlserver.os.wait.duration doesn't have an attribute %v, valid attributes: [wait.category, wait.type]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SqlserverPageBufferCacheFreeListStallsRateConfig provides config for the sqlserver.page.buffer_cache.free_list.stalls.rate metric.
type SqlserverPageBufferCacheFreeListStallsRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverPageBufferCacheFreeListStallsRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverPageBufferCacheHitRatioConfig provides config for the sqlserver.page.buffer_cache.hit_ratio metric.
type SqlserverPageBufferCacheHitRatioConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverPageBufferCacheHitRatioConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverPageCheckpointFlushRateConfig provides config for the sqlserver.page.checkpoint.flush.rate metric.
type SqlserverPageCheckpointFlushRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverPageCheckpointFlushRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverPageLazyWriteRateConfig provides config for the sqlserver.page.lazy_write.rate metric.
type SqlserverPageLazyWriteRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverPageLazyWriteRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverPageLifeExpectancyAttributeKey specifies the key of an attribute for the sqlserver.page.life_expectancy metric.
type SqlserverPageLifeExpectancyAttributeKey string

const (
	SqlserverPageLifeExpectancyAttributeKeyPerformanceCounterObjectName SqlserverPageLifeExpectancyAttributeKey = "performance_counter.object_name"
)

// SqlserverPageLifeExpectancyConfig provides config for the sqlserver.page.life_expectancy metric.
type SqlserverPageLifeExpectancyConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                    `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SqlserverPageLifeExpectancyAttributeKey `mapstructure:"attributes"`
}

func (ms *SqlserverPageLifeExpectancyConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SqlserverPageLifeExpectancyConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SqlserverPageLifeExpectancyAttributeKeyPerformanceCounterObjectName:
		default:
			return fmt.Errorf("metric sqlserver.page.life_expectancy doesn't have an attribute %v, valid attributes: [performance_counter.object_name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SqlserverPageLookupRateConfig provides config for the sqlserver.page.lookup.rate metric.
type SqlserverPageLookupRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverPageLookupRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverPageOperationRateAttributeKey specifies the key of an attribute for the sqlserver.page.operation.rate metric.
type SqlserverPageOperationRateAttributeKey string

const (
	SqlserverPageOperationRateAttributeKeyPageOperations SqlserverPageOperationRateAttributeKey = "type"
)

// SqlserverPageOperationRateConfig provides config for the sqlserver.page.operation.rate metric.
type SqlserverPageOperationRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                   `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SqlserverPageOperationRateAttributeKey `mapstructure:"attributes"`
}

func (ms *SqlserverPageOperationRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SqlserverPageOperationRateConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SqlserverPageOperationRateAttributeKeyPageOperations:
		default:
			return fmt.Errorf("metric sqlserver.page.operation.rate doesn't have an attribute %v, valid attributes: [type]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SqlserverPageSplitRateConfig provides config for the sqlserver.page.split.rate metric.
type SqlserverPageSplitRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverPageSplitRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverProcessesBlockedConfig provides config for the sqlserver.processes.blocked metric.
type SqlserverProcessesBlockedConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverProcessesBlockedConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverReplicaDataRateAttributeKey specifies the key of an attribute for the sqlserver.replica.data.rate metric.
type SqlserverReplicaDataRateAttributeKey string

const (
	SqlserverReplicaDataRateAttributeKeyReplicaDirection SqlserverReplicaDataRateAttributeKey = "replica.direction"
)

// SqlserverReplicaDataRateConfig provides config for the sqlserver.replica.data.rate metric.
type SqlserverReplicaDataRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                 `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SqlserverReplicaDataRateAttributeKey `mapstructure:"attributes"`
}

func (ms *SqlserverReplicaDataRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SqlserverReplicaDataRateConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SqlserverReplicaDataRateAttributeKeyReplicaDirection:
		default:
			return fmt.Errorf("metric sqlserver.replica.data.rate doesn't have an attribute %v, valid attributes: [replica.direction]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SqlserverResourcePoolDiskOperationsAttributeKey specifies the key of an attribute for the sqlserver.resource_pool.disk.operations metric.
type SqlserverResourcePoolDiskOperationsAttributeKey string

const (
	SqlserverResourcePoolDiskOperationsAttributeKeyDirection SqlserverResourcePoolDiskOperationsAttributeKey = "direction"
)

// SqlserverResourcePoolDiskOperationsConfig provides config for the sqlserver.resource_pool.disk.operations metric.
type SqlserverResourcePoolDiskOperationsConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                            `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SqlserverResourcePoolDiskOperationsAttributeKey `mapstructure:"attributes"`
}

func (ms *SqlserverResourcePoolDiskOperationsConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SqlserverResourcePoolDiskOperationsConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SqlserverResourcePoolDiskOperationsAttributeKeyDirection:
		default:
			return fmt.Errorf("metric sqlserver.resource_pool.disk.operations doesn't have an attribute %v, valid attributes: [direction]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SqlserverResourcePoolDiskThrottledReadRateConfig provides config for the sqlserver.resource_pool.disk.throttled.read.rate metric.
type SqlserverResourcePoolDiskThrottledReadRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverResourcePoolDiskThrottledReadRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverResourcePoolDiskThrottledWriteRateConfig provides config for the sqlserver.resource_pool.disk.throttled.write.rate metric.
type SqlserverResourcePoolDiskThrottledWriteRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverResourcePoolDiskThrottledWriteRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverTableCountAttributeKey specifies the key of an attribute for the sqlserver.table.count metric.
type SqlserverTableCountAttributeKey string

const (
	SqlserverTableCountAttributeKeyTableState  SqlserverTableCountAttributeKey = "table.state"
	SqlserverTableCountAttributeKeyTableStatus SqlserverTableCountAttributeKey = "table.status"
)

// SqlserverTableCountConfig provides config for the sqlserver.table.count metric.
type SqlserverTableCountConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                            `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SqlserverTableCountAttributeKey `mapstructure:"attributes"`
}

func (ms *SqlserverTableCountConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SqlserverTableCountConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SqlserverTableCountAttributeKeyTableState, SqlserverTableCountAttributeKeyTableStatus:
		default:
			return fmt.Errorf("metric sqlserver.table.count doesn't have an attribute %v, valid attributes: [table.state, table.status]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SqlserverTransactionDelayConfig provides config for the sqlserver.transaction.delay metric.
type SqlserverTransactionDelayConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverTransactionDelayConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverTransactionMirrorWriteRateConfig provides config for the sqlserver.transaction.mirror_write.rate metric.
type SqlserverTransactionMirrorWriteRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverTransactionMirrorWriteRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverTransactionRateConfig provides config for the sqlserver.transaction.rate metric.
type SqlserverTransactionRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverTransactionRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverTransactionWriteRateConfig provides config for the sqlserver.transaction.write.rate metric.
type SqlserverTransactionWriteRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverTransactionWriteRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverTransactionLogFlushDataRateConfig provides config for the sqlserver.transaction_log.flush.data.rate metric.
type SqlserverTransactionLogFlushDataRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverTransactionLogFlushDataRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverTransactionLogFlushRateConfig provides config for the sqlserver.transaction_log.flush.rate metric.
type SqlserverTransactionLogFlushRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverTransactionLogFlushRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverTransactionLogFlushWaitRateConfig provides config for the sqlserver.transaction_log.flush.wait.rate metric.
type SqlserverTransactionLogFlushWaitRateConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverTransactionLogFlushWaitRateConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverTransactionLogGrowthCountConfig provides config for the sqlserver.transaction_log.growth.count metric.
type SqlserverTransactionLogGrowthCountConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverTransactionLogGrowthCountConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverTransactionLogShrinkCountConfig provides config for the sqlserver.transaction_log.shrink.count metric.
type SqlserverTransactionLogShrinkCountConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverTransactionLogShrinkCountConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverTransactionLogUsageConfig provides config for the sqlserver.transaction_log.usage metric.
type SqlserverTransactionLogUsageConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverTransactionLogUsageConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SqlserverUserConnectionCountConfig provides config for the sqlserver.user.connection.count metric.
type SqlserverUserConnectionCountConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SqlserverUserConnectionCountConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for sqlserver metrics.
type MetricsConfig struct {
	SqlserverBatchRequestRate                   SqlserverBatchRequestRateConfig                   `mapstructure:"sqlserver.batch.request.rate"`
	SqlserverBatchSQLCompilationRate            SqlserverBatchSQLCompilationRateConfig            `mapstructure:"sqlserver.batch.sql_compilation.rate"`
	SqlserverBatchSQLRecompilationRate          SqlserverBatchSQLRecompilationRateConfig          `mapstructure:"sqlserver.batch.sql_recompilation.rate"`
	SqlserverComputerUptime                     SqlserverComputerUptimeConfig                     `mapstructure:"sqlserver.computer.uptime"`
	SqlserverCPUCount                           SqlserverCPUCountConfig                           `mapstructure:"sqlserver.cpu.count"`
	SqlserverDatabaseBackupOrRestoreRate        SqlserverDatabaseBackupOrRestoreRateConfig        `mapstructure:"sqlserver.database.backup_or_restore.rate"`
	SqlserverDatabaseCount                      SqlserverDatabaseCountConfig                      `mapstructure:"sqlserver.database.count"`
	SqlserverDatabaseExecutionErrors            SqlserverDatabaseExecutionErrorsConfig            `mapstructure:"sqlserver.database.execution.errors"`
	SqlserverDatabaseFullScanRate               SqlserverDatabaseFullScanRateConfig               `mapstructure:"sqlserver.database.full_scan.rate"`
	SqlserverDatabaseIo                         SqlserverDatabaseIoConfig                         `mapstructure:"sqlserver.database.io"`
	SqlserverDatabaseLatency                    SqlserverDatabaseLatencyConfig                    `mapstructure:"sqlserver.database.latency"`
	SqlserverDatabaseOperations                 SqlserverDatabaseOperationsConfig                 `mapstructure:"sqlserver.database.operations"`
	SqlserverDatabaseTempdbSpace                SqlserverDatabaseTempdbSpaceConfig                `mapstructure:"sqlserver.database.tempdb.space"`
	SqlserverDatabaseTempdbVersionStoreSize     SqlserverDatabaseTempdbVersionStoreSizeConfig     `mapstructure:"sqlserver.database.tempdb.version_store.size"`
	SqlserverDeadlockRate                       SqlserverDeadlockRateConfig                       `mapstructure:"sqlserver.deadlock.rate"`
	SqlserverIndexSearchRate                    SqlserverIndexSearchRateConfig                    `mapstructure:"sqlserver.index.search.rate"`
	SqlserverLockTimeoutRate                    SqlserverLockTimeoutRateConfig                    `mapstructure:"sqlserver.lock.timeout.rate"`
	SqlserverLockWaitCount                      SqlserverLockWaitCountConfig                      `mapstructure:"sqlserver.lock.wait.count"`
	SqlserverLockWaitRate                       SqlserverLockWaitRateConfig                       `mapstructure:"sqlserver.lock.wait.rate"`
	SqlserverLockWaitTimeAvg                    SqlserverLockWaitTimeAvgConfig                    `mapstructure:"sqlserver.lock.wait_time.avg"`
	SqlserverLoginRate                          SqlserverLoginRateConfig                          `mapstructure:"sqlserver.login.rate"`
	SqlserverLogoutRate                         SqlserverLogoutRateConfig                         `mapstructure:"sqlserver.logout.rate"`
	SqlserverMemoryGrantsPendingCount           SqlserverMemoryGrantsPendingCountConfig           `mapstructure:"sqlserver.memory.grants.pending.count"`
	SqlserverMemoryUsage                        SqlserverMemoryUsageConfig                        `mapstructure:"sqlserver.memory.usage"`
	SqlserverOsWaitDuration                     SqlserverOsWaitDurationConfig                     `mapstructure:"sqlserver.os.wait.duration"`
	SqlserverPageBufferCacheFreeListStallsRate  SqlserverPageBufferCacheFreeListStallsRateConfig  `mapstructure:"sqlserver.page.buffer_cache.free_list.stalls.rate"`
	SqlserverPageBufferCacheHitRatio            SqlserverPageBufferCacheHitRatioConfig            `mapstructure:"sqlserver.page.buffer_cache.hit_ratio"`
	SqlserverPageCheckpointFlushRate            SqlserverPageCheckpointFlushRateConfig            `mapstructure:"sqlserver.page.checkpoint.flush.rate"`
	SqlserverPageLazyWriteRate                  SqlserverPageLazyWriteRateConfig                  `mapstructure:"sqlserver.page.lazy_write.rate"`
	SqlserverPageLifeExpectancy                 SqlserverPageLifeExpectancyConfig                 `mapstructure:"sqlserver.page.life_expectancy"`
	SqlserverPageLookupRate                     SqlserverPageLookupRateConfig                     `mapstructure:"sqlserver.page.lookup.rate"`
	SqlserverPageOperationRate                  SqlserverPageOperationRateConfig                  `mapstructure:"sqlserver.page.operation.rate"`
	SqlserverPageSplitRate                      SqlserverPageSplitRateConfig                      `mapstructure:"sqlserver.page.split.rate"`
	SqlserverProcessesBlocked                   SqlserverProcessesBlockedConfig                   `mapstructure:"sqlserver.processes.blocked"`
	SqlserverReplicaDataRate                    SqlserverReplicaDataRateConfig                    `mapstructure:"sqlserver.replica.data.rate"`
	SqlserverResourcePoolDiskOperations         SqlserverResourcePoolDiskOperationsConfig         `mapstructure:"sqlserver.resource_pool.disk.operations"`
	SqlserverResourcePoolDiskThrottledReadRate  SqlserverResourcePoolDiskThrottledReadRateConfig  `mapstructure:"sqlserver.resource_pool.disk.throttled.read.rate"`
	SqlserverResourcePoolDiskThrottledWriteRate SqlserverResourcePoolDiskThrottledWriteRateConfig `mapstructure:"sqlserver.resource_pool.disk.throttled.write.rate"`
	SqlserverTableCount                         SqlserverTableCountConfig                         `mapstructure:"sqlserver.table.count"`
	SqlserverTransactionDelay                   SqlserverTransactionDelayConfig                   `mapstructure:"sqlserver.transaction.delay"`
	SqlserverTransactionMirrorWriteRate         SqlserverTransactionMirrorWriteRateConfig         `mapstructure:"sqlserver.transaction.mirror_write.rate"`
	SqlserverTransactionRate                    SqlserverTransactionRateConfig                    `mapstructure:"sqlserver.transaction.rate"`
	SqlserverTransactionWriteRate               SqlserverTransactionWriteRateConfig               `mapstructure:"sqlserver.transaction.write.rate"`
	SqlserverTransactionLogFlushDataRate        SqlserverTransactionLogFlushDataRateConfig        `mapstructure:"sqlserver.transaction_log.flush.data.rate"`
	SqlserverTransactionLogFlushRate            SqlserverTransactionLogFlushRateConfig            `mapstructure:"sqlserver.transaction_log.flush.rate"`
	SqlserverTransactionLogFlushWaitRate        SqlserverTransactionLogFlushWaitRateConfig        `mapstructure:"sqlserver.transaction_log.flush.wait.rate"`
	SqlserverTransactionLogGrowthCount          SqlserverTransactionLogGrowthCountConfig          `mapstructure:"sqlserver.transaction_log.growth.count"`
	SqlserverTransactionLogShrinkCount          SqlserverTransactionLogShrinkCountConfig          `mapstructure:"sqlserver.transaction_log.shrink.count"`
	SqlserverTransactionLogUsage                SqlserverTransactionLogUsageConfig                `mapstructure:"sqlserver.transaction_log.usage"`
	SqlserverUserConnectionCount                SqlserverUserConnectionCountConfig                `mapstructure:"sqlserver.user.connection.count"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		SqlserverBatchRequestRate: SqlserverBatchRequestRateConfig{
			Enabled: true,
		},
		SqlserverBatchSQLCompilationRate: SqlserverBatchSQLCompilationRateConfig{
			Enabled: true,
		},
		SqlserverBatchSQLRecompilationRate: SqlserverBatchSQLRecompilationRateConfig{
			Enabled: true,
		},
		SqlserverComputerUptime: SqlserverComputerUptimeConfig{
			Enabled: false,
		},
		SqlserverCPUCount: SqlserverCPUCountConfig{
			Enabled: false,
		},
		SqlserverDatabaseBackupOrRestoreRate: SqlserverDatabaseBackupOrRestoreRateConfig{
			Enabled: false,
		},
		SqlserverDatabaseCount: SqlserverDatabaseCountConfig{
			Enabled:             false,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []SqlserverDatabaseCountAttributeKey{SqlserverDatabaseCountAttributeKeyDatabaseStatus},
		},
		SqlserverDatabaseExecutionErrors: SqlserverDatabaseExecutionErrorsConfig{
			Enabled: false,
		},
		SqlserverDatabaseFullScanRate: SqlserverDatabaseFullScanRateConfig{
			Enabled: false,
		},
		SqlserverDatabaseIo: SqlserverDatabaseIoConfig{
			Enabled:             false,
			AggregationStrategy: AggregationStrategySum,
			EnabledAttributes:   []SqlserverDatabaseIoAttributeKey{SqlserverDatabaseIoAttributeKeyPhysicalFilename, SqlserverDatabaseIoAttributeKeyLogicalFilename, SqlserverDatabaseIoAttributeKeyFileType, SqlserverDatabaseIoAttributeKeyDirection},
		},
		SqlserverDatabaseLatency: SqlserverDatabaseLatencyConfig{
			Enabled:             false,
			AggregationStrategy: AggregationStrategySum,
			EnabledAttributes:   []SqlserverDatabaseLatencyAttributeKey{SqlserverDatabaseLatencyAttributeKeyPhysicalFilename, SqlserverDatabaseLatencyAttributeKeyLogicalFilename, SqlserverDatabaseLatencyAttributeKeyFileType, SqlserverDatabaseLatencyAttributeKeyDirection},
		},
		SqlserverDatabaseOperations: SqlserverDatabaseOperationsConfig{
			Enabled:             false,
			AggregationStrategy: AggregationStrategySum,
			EnabledAttributes:   []SqlserverDatabaseOperationsAttributeKey{SqlserverDatabaseOperationsAttributeKeyPhysicalFilename, SqlserverDatabaseOperationsAttributeKeyLogicalFilename, SqlserverDatabaseOperationsAttributeKeyFileType, SqlserverDatabaseOperationsAttributeKeyDirection},
		},
		SqlserverDatabaseTempdbSpace: SqlserverDatabaseTempdbSpaceConfig{
			Enabled:             false,
			AggregationStrategy: AggregationStrategySum,
			EnabledAttributes:   []SqlserverDatabaseTempdbSpaceAttributeKey{SqlserverDatabaseTempdbSpaceAttributeKeyTempdbState},
		},
		SqlserverDatabaseTempdbVersionStoreSize: SqlserverDatabaseTempdbVersionStoreSizeConfig{
			Enabled: false,
		},
		SqlserverDeadlockRate: SqlserverDeadlockRateConfig{
			Enabled: false,
		},
		SqlserverIndexSearchRate: SqlserverIndexSearchRateConfig{
			Enabled: false,
		},
		SqlserverLockTimeoutRate: SqlserverLockTimeoutRateConfig{
			Enabled: false,
		},
		SqlserverLockWaitCount: SqlserverLockWaitCountConfig{
			Enabled: false,
		},
		SqlserverLockWaitRate: SqlserverLockWaitRateConfig{
			Enabled: true,
		},
		SqlserverLockWaitTimeAvg: SqlserverLockWaitTimeAvgConfig{
			Enabled: true,
		},
		SqlserverLoginRate: SqlserverLoginRateConfig{
			Enabled: false,
		},
		SqlserverLogoutRate: SqlserverLogoutRateConfig{
			Enabled: false,
		},
		SqlserverMemoryGrantsPendingCount: SqlserverMemoryGrantsPendingCountConfig{
			Enabled: false,
		},
		SqlserverMemoryUsage: SqlserverMemoryUsageConfig{
			Enabled: false,
		},
		SqlserverOsWaitDuration: SqlserverOsWaitDurationConfig{
			Enabled:             false,
			AggregationStrategy: AggregationStrategySum,
			EnabledAttributes:   []SqlserverOsWaitDurationAttributeKey{SqlserverOsWaitDurationAttributeKeyWaitCategory, SqlserverOsWaitDurationAttributeKeyWaitType},
		},
		SqlserverPageBufferCacheFreeListStallsRate: SqlserverPageBufferCacheFreeListStallsRateConfig{
			Enabled: false,
		},
		SqlserverPageBufferCacheHitRatio: SqlserverPageBufferCacheHitRatioConfig{
			Enabled: true,
		},
		SqlserverPageCheckpointFlushRate: SqlserverPageCheckpointFlushRateConfig{
			Enabled: true,
		},
		SqlserverPageLazyWriteRate: SqlserverPageLazyWriteRateConfig{
			Enabled: true,
		},
		SqlserverPageLifeExpectancy: SqlserverPageLifeExpectancyConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []SqlserverPageLifeExpectancyAttributeKey{SqlserverPageLifeExpectancyAttributeKeyPerformanceCounterObjectName},
		},
		SqlserverPageLookupRate: SqlserverPageLookupRateConfig{
			Enabled: false,
		},
		SqlserverPageOperationRate: SqlserverPageOperationRateConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []SqlserverPageOperationRateAttributeKey{SqlserverPageOperationRateAttributeKeyPageOperations},
		},
		SqlserverPageSplitRate: SqlserverPageSplitRateConfig{
			Enabled: true,
		},
		SqlserverProcessesBlocked: SqlserverProcessesBlockedConfig{
			Enabled: false,
		},
		SqlserverReplicaDataRate: SqlserverReplicaDataRateConfig{
			Enabled:             false,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []SqlserverReplicaDataRateAttributeKey{SqlserverReplicaDataRateAttributeKeyReplicaDirection},
		},
		SqlserverResourcePoolDiskOperations: SqlserverResourcePoolDiskOperationsConfig{
			Enabled:             false,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []SqlserverResourcePoolDiskOperationsAttributeKey{SqlserverResourcePoolDiskOperationsAttributeKeyDirection},
		},
		SqlserverResourcePoolDiskThrottledReadRate: SqlserverResourcePoolDiskThrottledReadRateConfig{
			Enabled: false,
		},
		SqlserverResourcePoolDiskThrottledWriteRate: SqlserverResourcePoolDiskThrottledWriteRateConfig{
			Enabled: false,
		},
		SqlserverTableCount: SqlserverTableCountConfig{
			Enabled:             false,
			AggregationStrategy: AggregationStrategySum,
			EnabledAttributes:   []SqlserverTableCountAttributeKey{SqlserverTableCountAttributeKeyTableState, SqlserverTableCountAttributeKeyTableStatus},
		},
		SqlserverTransactionDelay: SqlserverTransactionDelayConfig{
			Enabled: false,
		},
		SqlserverTransactionMirrorWriteRate: SqlserverTransactionMirrorWriteRateConfig{
			Enabled: false,
		},
		SqlserverTransactionRate: SqlserverTransactionRateConfig{
			Enabled: true,
		},
		SqlserverTransactionWriteRate: SqlserverTransactionWriteRateConfig{
			Enabled: true,
		},
		SqlserverTransactionLogFlushDataRate: SqlserverTransactionLogFlushDataRateConfig{
			Enabled: true,
		},
		SqlserverTransactionLogFlushRate: SqlserverTransactionLogFlushRateConfig{
			Enabled: true,
		},
		SqlserverTransactionLogFlushWaitRate: SqlserverTransactionLogFlushWaitRateConfig{
			Enabled: true,
		},
		SqlserverTransactionLogGrowthCount: SqlserverTransactionLogGrowthCountConfig{
			Enabled: true,
		},
		SqlserverTransactionLogShrinkCount: SqlserverTransactionLogShrinkCountConfig{
			Enabled: true,
		},
		SqlserverTransactionLogUsage: SqlserverTransactionLogUsageConfig{
			Enabled: true,
		},
		SqlserverUserConnectionCount: SqlserverUserConnectionCountConfig{
			Enabled: true,
		},
	}
}

// EventConfig provides common config for a particular event.
type EventConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ec *EventConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ec)
	if err != nil {
		return err
	}
	ec.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// EventsConfig provides config for sqlserver events.
type EventsConfig struct {
	DbServerQuerySample EventConfig `mapstructure:"db.server.query_sample"`
	DbServerTopQuery    EventConfig `mapstructure:"db.server.top_query"`
}

func DefaultEventsConfig() EventsConfig {
	return EventsConfig{
		DbServerQuerySample: EventConfig{
			Enabled: false,
		},
		DbServerTopQuery: EventConfig{
			Enabled: false,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`
	// Experimental: EventsInclude defines a list of filters for attribute values.
	// If the list is not empty, only events with matching resource attribute values will be emitted.
	EventsInclude []filter.Config `mapstructure:"events_include"`
	// Experimental: EventsExclude defines a list of filters for attribute values.
	// If the list is not empty, events with matching resource attribute values will not be emitted.
	// EventsInclude has higher priority than EventsExclude.
	EventsExclude []filter.Config `mapstructure:"events_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for sqlserver resource attributes.
type ResourceAttributesConfig struct {
	HostName              ResourceAttributeConfig `mapstructure:"host.name"`
	ServerAddress         ResourceAttributeConfig `mapstructure:"server.address"`
	ServerPort            ResourceAttributeConfig `mapstructure:"server.port"`
	ServiceInstanceID     ResourceAttributeConfig `mapstructure:"service.instance.id"`
	SqlserverComputerName ResourceAttributeConfig `mapstructure:"sqlserver.computer.name"`
	SqlserverDatabaseName ResourceAttributeConfig `mapstructure:"sqlserver.database.name"`
	SqlserverInstanceName ResourceAttributeConfig `mapstructure:"sqlserver.instance.name"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		HostName: ResourceAttributeConfig{
			Enabled: true,
		},
		ServerAddress: ResourceAttributeConfig{
			Enabled: false,
		},
		ServerPort: ResourceAttributeConfig{
			Enabled: false,
		},
		ServiceInstanceID: ResourceAttributeConfig{
			Enabled: true,
		},
		SqlserverComputerName: ResourceAttributeConfig{
			Enabled: false,
		},
		SqlserverDatabaseName: ResourceAttributeConfig{
			Enabled: true,
		},
		SqlserverInstanceName: ResourceAttributeConfig{
			Enabled: false,
		},
	}
}

// MetricsBuilderConfig is a configuration for sqlserver metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}

// LogsBuilderConfig is a configuration for sqlserver logs builder.
type LogsBuilderConfig struct {
	Events             EventsConfig             `mapstructure:"events"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultLogsBuilderConfig() LogsBuilderConfig {
	return LogsBuilderConfig{
		Events:             DefaultEventsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
