// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"fmt"
	"slices"

	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string   `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []string `mapstructure:"attributes"`
	definedAttributes   []string
	requiredAttributes  []string
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	for _, val := range ms.EnabledAttributes {
		if !slices.Contains(ms.definedAttributes, val) {
			return fmt.Errorf("%v is not defined in metadata.yaml", val)
		}
	}

	for _, val := range ms.requiredAttributes {
		if !slices.Contains(ms.EnabledAttributes, val) {
			return fmt.Errorf("`attributes` field must contain required attribute: %v", val)
		}
	}

	if ms.AggregationStrategy != AggregationStrategySum &&
		ms.AggregationStrategy != AggregationStrategyAvg &&
		ms.AggregationStrategy != AggregationStrategyMin &&
		ms.AggregationStrategy != AggregationStrategyMax {
		return fmt.Errorf("invalid aggregation strategy set: '%v'", ms.AggregationStrategy)
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// AttributeConfig holds configuration information for a particular metric.
type AttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
}

// MetricsConfig provides config for docker_stats metrics.
type MetricsConfig struct {
	ContainerBlockioIoMergedRecursive          MetricConfig `mapstructure:"container.blockio.io_merged_recursive"`
	ContainerBlockioIoQueuedRecursive          MetricConfig `mapstructure:"container.blockio.io_queued_recursive"`
	ContainerBlockioIoServiceBytesRecursive    MetricConfig `mapstructure:"container.blockio.io_service_bytes_recursive"`
	ContainerBlockioIoServiceTimeRecursive     MetricConfig `mapstructure:"container.blockio.io_service_time_recursive"`
	ContainerBlockioIoServicedRecursive        MetricConfig `mapstructure:"container.blockio.io_serviced_recursive"`
	ContainerBlockioIoTimeRecursive            MetricConfig `mapstructure:"container.blockio.io_time_recursive"`
	ContainerBlockioIoWaitTimeRecursive        MetricConfig `mapstructure:"container.blockio.io_wait_time_recursive"`
	ContainerBlockioSectorsRecursive           MetricConfig `mapstructure:"container.blockio.sectors_recursive"`
	ContainerCPULimit                          MetricConfig `mapstructure:"container.cpu.limit"`
	ContainerCPULogicalCount                   MetricConfig `mapstructure:"container.cpu.logical.count"`
	ContainerCPUShares                         MetricConfig `mapstructure:"container.cpu.shares"`
	ContainerCPUThrottlingDataPeriods          MetricConfig `mapstructure:"container.cpu.throttling_data.periods"`
	ContainerCPUThrottlingDataThrottledPeriods MetricConfig `mapstructure:"container.cpu.throttling_data.throttled_periods"`
	ContainerCPUThrottlingDataThrottledTime    MetricConfig `mapstructure:"container.cpu.throttling_data.throttled_time"`
	ContainerCPUUsageKernelmode                MetricConfig `mapstructure:"container.cpu.usage.kernelmode"`
	ContainerCPUUsagePercpu                    MetricConfig `mapstructure:"container.cpu.usage.percpu"`
	ContainerCPUUsageSystem                    MetricConfig `mapstructure:"container.cpu.usage.system"`
	ContainerCPUUsageTotal                     MetricConfig `mapstructure:"container.cpu.usage.total"`
	ContainerCPUUsageUsermode                  MetricConfig `mapstructure:"container.cpu.usage.usermode"`
	ContainerCPUUtilization                    MetricConfig `mapstructure:"container.cpu.utilization"`
	ContainerMemoryActiveAnon                  MetricConfig `mapstructure:"container.memory.active_anon"`
	ContainerMemoryActiveFile                  MetricConfig `mapstructure:"container.memory.active_file"`
	ContainerMemoryAnon                        MetricConfig `mapstructure:"container.memory.anon"`
	ContainerMemoryCache                       MetricConfig `mapstructure:"container.memory.cache"`
	ContainerMemoryDirty                       MetricConfig `mapstructure:"container.memory.dirty"`
	ContainerMemoryFails                       MetricConfig `mapstructure:"container.memory.fails"`
	ContainerMemoryFile                        MetricConfig `mapstructure:"container.memory.file"`
	ContainerMemoryHierarchicalMemoryLimit     MetricConfig `mapstructure:"container.memory.hierarchical_memory_limit"`
	ContainerMemoryHierarchicalMemswLimit      MetricConfig `mapstructure:"container.memory.hierarchical_memsw_limit"`
	ContainerMemoryInactiveAnon                MetricConfig `mapstructure:"container.memory.inactive_anon"`
	ContainerMemoryInactiveFile                MetricConfig `mapstructure:"container.memory.inactive_file"`
	ContainerMemoryMappedFile                  MetricConfig `mapstructure:"container.memory.mapped_file"`
	ContainerMemoryPercent                     MetricConfig `mapstructure:"container.memory.percent"`
	ContainerMemoryPgfault                     MetricConfig `mapstructure:"container.memory.pgfault"`
	ContainerMemoryPgmajfault                  MetricConfig `mapstructure:"container.memory.pgmajfault"`
	ContainerMemoryPgpgin                      MetricConfig `mapstructure:"container.memory.pgpgin"`
	ContainerMemoryPgpgout                     MetricConfig `mapstructure:"container.memory.pgpgout"`
	ContainerMemoryRss                         MetricConfig `mapstructure:"container.memory.rss"`
	ContainerMemoryRssHuge                     MetricConfig `mapstructure:"container.memory.rss_huge"`
	ContainerMemoryTotalActiveAnon             MetricConfig `mapstructure:"container.memory.total_active_anon"`
	ContainerMemoryTotalActiveFile             MetricConfig `mapstructure:"container.memory.total_active_file"`
	ContainerMemoryTotalCache                  MetricConfig `mapstructure:"container.memory.total_cache"`
	ContainerMemoryTotalDirty                  MetricConfig `mapstructure:"container.memory.total_dirty"`
	ContainerMemoryTotalInactiveAnon           MetricConfig `mapstructure:"container.memory.total_inactive_anon"`
	ContainerMemoryTotalInactiveFile           MetricConfig `mapstructure:"container.memory.total_inactive_file"`
	ContainerMemoryTotalMappedFile             MetricConfig `mapstructure:"container.memory.total_mapped_file"`
	ContainerMemoryTotalPgfault                MetricConfig `mapstructure:"container.memory.total_pgfault"`
	ContainerMemoryTotalPgmajfault             MetricConfig `mapstructure:"container.memory.total_pgmajfault"`
	ContainerMemoryTotalPgpgin                 MetricConfig `mapstructure:"container.memory.total_pgpgin"`
	ContainerMemoryTotalPgpgout                MetricConfig `mapstructure:"container.memory.total_pgpgout"`
	ContainerMemoryTotalRss                    MetricConfig `mapstructure:"container.memory.total_rss"`
	ContainerMemoryTotalRssHuge                MetricConfig `mapstructure:"container.memory.total_rss_huge"`
	ContainerMemoryTotalUnevictable            MetricConfig `mapstructure:"container.memory.total_unevictable"`
	ContainerMemoryTotalWriteback              MetricConfig `mapstructure:"container.memory.total_writeback"`
	ContainerMemoryUnevictable                 MetricConfig `mapstructure:"container.memory.unevictable"`
	ContainerMemoryUsageLimit                  MetricConfig `mapstructure:"container.memory.usage.limit"`
	ContainerMemoryUsageMax                    MetricConfig `mapstructure:"container.memory.usage.max"`
	ContainerMemoryUsageTotal                  MetricConfig `mapstructure:"container.memory.usage.total"`
	ContainerMemoryWriteback                   MetricConfig `mapstructure:"container.memory.writeback"`
	ContainerNetworkIoUsageRxBytes             MetricConfig `mapstructure:"container.network.io.usage.rx_bytes"`
	ContainerNetworkIoUsageRxDropped           MetricConfig `mapstructure:"container.network.io.usage.rx_dropped"`
	ContainerNetworkIoUsageRxErrors            MetricConfig `mapstructure:"container.network.io.usage.rx_errors"`
	ContainerNetworkIoUsageRxPackets           MetricConfig `mapstructure:"container.network.io.usage.rx_packets"`
	ContainerNetworkIoUsageTxBytes             MetricConfig `mapstructure:"container.network.io.usage.tx_bytes"`
	ContainerNetworkIoUsageTxDropped           MetricConfig `mapstructure:"container.network.io.usage.tx_dropped"`
	ContainerNetworkIoUsageTxErrors            MetricConfig `mapstructure:"container.network.io.usage.tx_errors"`
	ContainerNetworkIoUsageTxPackets           MetricConfig `mapstructure:"container.network.io.usage.tx_packets"`
	ContainerPidsCount                         MetricConfig `mapstructure:"container.pids.count"`
	ContainerPidsLimit                         MetricConfig `mapstructure:"container.pids.limit"`
	ContainerRestarts                          MetricConfig `mapstructure:"container.restarts"`
	ContainerUptime                            MetricConfig `mapstructure:"container.uptime"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		ContainerBlockioIoMergedRecursive: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"device_major", "device_minor", "operation"},
			EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
		},
		ContainerBlockioIoQueuedRecursive: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"device_major", "device_minor", "operation"},
			EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
		},
		ContainerBlockioIoServiceBytesRecursive: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"device_major", "device_minor", "operation"},
			EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
		},
		ContainerBlockioIoServiceTimeRecursive: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"device_major", "device_minor", "operation"},
			EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
		},
		ContainerBlockioIoServicedRecursive: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"device_major", "device_minor", "operation"},
			EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
		},
		ContainerBlockioIoTimeRecursive: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"device_major", "device_minor", "operation"},
			EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
		},
		ContainerBlockioIoWaitTimeRecursive: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"device_major", "device_minor", "operation"},
			EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
		},
		ContainerBlockioSectorsRecursive: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"device_major", "device_minor", "operation"},
			EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
		},
		ContainerCPULimit: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerCPULogicalCount: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerCPUShares: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerCPUThrottlingDataPeriods: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerCPUThrottlingDataThrottledPeriods: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerCPUThrottlingDataThrottledTime: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerCPUUsageKernelmode: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerCPUUsagePercpu: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"core"},
			EnabledAttributes:   []string{"core"},
		},
		ContainerCPUUsageSystem: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerCPUUsageTotal: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerCPUUsageUsermode: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerCPUUtilization: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryActiveAnon: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryActiveFile: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryAnon: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryCache: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryDirty: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryFails: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryFile: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryHierarchicalMemoryLimit: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryHierarchicalMemswLimit: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryInactiveAnon: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryInactiveFile: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryMappedFile: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryPercent: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryPgfault: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryPgmajfault: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryPgpgin: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryPgpgout: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryRss: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryRssHuge: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryTotalActiveAnon: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryTotalActiveFile: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryTotalCache: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryTotalDirty: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryTotalInactiveAnon: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryTotalInactiveFile: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryTotalMappedFile: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryTotalPgfault: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryTotalPgmajfault: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryTotalPgpgin: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryTotalPgpgout: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryTotalRss: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryTotalRssHuge: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryTotalUnevictable: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryTotalWriteback: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryUnevictable: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryUsageLimit: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryUsageMax: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryUsageTotal: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerMemoryWriteback: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerNetworkIoUsageRxBytes: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"interface"},
			EnabledAttributes:   []string{"interface"},
		},
		ContainerNetworkIoUsageRxDropped: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"interface"},
			EnabledAttributes:   []string{"interface"},
		},
		ContainerNetworkIoUsageRxErrors: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"interface"},
			EnabledAttributes:   []string{"interface"},
		},
		ContainerNetworkIoUsageRxPackets: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"interface"},
			EnabledAttributes:   []string{"interface"},
		},
		ContainerNetworkIoUsageTxBytes: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"interface"},
			EnabledAttributes:   []string{"interface"},
		},
		ContainerNetworkIoUsageTxDropped: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"interface"},
			EnabledAttributes:   []string{"interface"},
		},
		ContainerNetworkIoUsageTxErrors: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"interface"},
			EnabledAttributes:   []string{"interface"},
		},
		ContainerNetworkIoUsageTxPackets: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"interface"},
			EnabledAttributes:   []string{"interface"},
		},
		ContainerPidsCount: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerPidsLimit: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerRestarts: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		ContainerUptime: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for docker_stats resource attributes.
type ResourceAttributesConfig struct {
	ContainerCommandLine ResourceAttributeConfig `mapstructure:"container.command_line"`
	ContainerHostname    ResourceAttributeConfig `mapstructure:"container.hostname"`
	ContainerID          ResourceAttributeConfig `mapstructure:"container.id"`
	ContainerImageID     ResourceAttributeConfig `mapstructure:"container.image.id"`
	ContainerImageName   ResourceAttributeConfig `mapstructure:"container.image.name"`
	ContainerName        ResourceAttributeConfig `mapstructure:"container.name"`
	ContainerRuntime     ResourceAttributeConfig `mapstructure:"container.runtime"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		ContainerCommandLine: ResourceAttributeConfig{
			Enabled: false,
		},
		ContainerHostname: ResourceAttributeConfig{
			Enabled: true,
		},
		ContainerID: ResourceAttributeConfig{
			Enabled: true,
		},
		ContainerImageID: ResourceAttributeConfig{
			Enabled: false,
		},
		ContainerImageName: ResourceAttributeConfig{
			Enabled: true,
		},
		ContainerName: ResourceAttributeConfig{
			Enabled: true,
		},
		ContainerRuntime: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for docker_stats metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
