// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: DefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					ContainerBlockioIoMergedRecursive: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
					},
					ContainerBlockioIoQueuedRecursive: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
					},
					ContainerBlockioIoServiceBytesRecursive: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
					},
					ContainerBlockioIoServiceTimeRecursive: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
					},
					ContainerBlockioIoServicedRecursive: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
					},
					ContainerBlockioIoTimeRecursive: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
					},
					ContainerBlockioIoWaitTimeRecursive: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
					},
					ContainerBlockioSectorsRecursive: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
					},
					ContainerCPULimit: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					ContainerCPULogicalCount: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					ContainerCPUShares: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					ContainerCPUThrottlingDataPeriods: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerCPUThrottlingDataThrottledPeriods: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerCPUThrottlingDataThrottledTime: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerCPUUsageKernelmode: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerCPUUsagePercpu: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"core"},
					},
					ContainerCPUUsageSystem: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerCPUUsageTotal: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerCPUUsageUsermode: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerCPUUtilization: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryActiveAnon: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryActiveFile: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryAnon: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryCache: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryDirty: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryFails: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryFile: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryHierarchicalMemoryLimit: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryHierarchicalMemswLimit: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryInactiveAnon: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryInactiveFile: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryMappedFile: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryPercent: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryPgfault: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryPgmajfault: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryPgpgin: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryPgpgout: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryRss: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryRssHuge: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalActiveAnon: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalActiveFile: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalCache: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalDirty: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalInactiveAnon: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalInactiveFile: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalMappedFile: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalPgfault: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalPgmajfault: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalPgpgin: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalPgpgout: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalRss: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalRssHuge: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalUnevictable: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalWriteback: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryUnevictable: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryUsageLimit: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryUsageMax: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryUsageTotal: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryWriteback: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerNetworkIoUsageRxBytes: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"interface"},
					},
					ContainerNetworkIoUsageRxDropped: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"interface"},
					},
					ContainerNetworkIoUsageRxErrors: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"interface"},
					},
					ContainerNetworkIoUsageRxPackets: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"interface"},
					},
					ContainerNetworkIoUsageTxBytes: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"interface"},
					},
					ContainerNetworkIoUsageTxDropped: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"interface"},
					},
					ContainerNetworkIoUsageTxErrors: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"interface"},
					},
					ContainerNetworkIoUsageTxPackets: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"interface"},
					},
					ContainerPidsCount: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerPidsLimit: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerRestarts: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerUptime: MetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					ContainerCommandLine: ResourceAttributeConfig{Enabled: true},
					ContainerHostname:    ResourceAttributeConfig{Enabled: true},
					ContainerID:          ResourceAttributeConfig{Enabled: true},
					ContainerImageID:     ResourceAttributeConfig{Enabled: true},
					ContainerImageName:   ResourceAttributeConfig{Enabled: true},
					ContainerName:        ResourceAttributeConfig{Enabled: true},
					ContainerRuntime:     ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					ContainerBlockioIoMergedRecursive: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
					},
					ContainerBlockioIoQueuedRecursive: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
					},
					ContainerBlockioIoServiceBytesRecursive: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
					},
					ContainerBlockioIoServiceTimeRecursive: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
					},
					ContainerBlockioIoServicedRecursive: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
					},
					ContainerBlockioIoTimeRecursive: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
					},
					ContainerBlockioIoWaitTimeRecursive: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
					},
					ContainerBlockioSectorsRecursive: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"device_major", "device_minor", "operation"},
					},
					ContainerCPULimit: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					ContainerCPULogicalCount: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					ContainerCPUShares: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					ContainerCPUThrottlingDataPeriods: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerCPUThrottlingDataThrottledPeriods: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerCPUThrottlingDataThrottledTime: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerCPUUsageKernelmode: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerCPUUsagePercpu: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"core"},
					},
					ContainerCPUUsageSystem: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerCPUUsageTotal: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerCPUUsageUsermode: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerCPUUtilization: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryActiveAnon: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryActiveFile: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryAnon: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryCache: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryDirty: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryFails: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryFile: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryHierarchicalMemoryLimit: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryHierarchicalMemswLimit: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryInactiveAnon: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryInactiveFile: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryMappedFile: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryPercent: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryPgfault: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryPgmajfault: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryPgpgin: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryPgpgout: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryRss: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryRssHuge: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalActiveAnon: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalActiveFile: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalCache: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalDirty: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalInactiveAnon: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalInactiveFile: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalMappedFile: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalPgfault: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalPgmajfault: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalPgpgin: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalPgpgout: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalRss: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalRssHuge: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalUnevictable: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryTotalWriteback: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryUnevictable: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryUsageLimit: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryUsageMax: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryUsageTotal: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerMemoryWriteback: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerNetworkIoUsageRxBytes: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"interface"},
					},
					ContainerNetworkIoUsageRxDropped: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"interface"},
					},
					ContainerNetworkIoUsageRxErrors: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"interface"},
					},
					ContainerNetworkIoUsageRxPackets: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"interface"},
					},
					ContainerNetworkIoUsageTxBytes: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"interface"},
					},
					ContainerNetworkIoUsageTxDropped: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"interface"},
					},
					ContainerNetworkIoUsageTxErrors: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"interface"},
					},
					ContainerNetworkIoUsageTxPackets: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{"interface"},
					},
					ContainerPidsCount: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerPidsLimit: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerRestarts: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []string{},
					},
					ContainerUptime: MetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []string{},
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					ContainerCommandLine: ResourceAttributeConfig{Enabled: false},
					ContainerHostname:    ResourceAttributeConfig{Enabled: false},
					ContainerID:          ResourceAttributeConfig{Enabled: false},
					ContainerImageID:     ResourceAttributeConfig{Enabled: false},
					ContainerImageName:   ResourceAttributeConfig{Enabled: false},
					ContainerName:        ResourceAttributeConfig{Enabled: false},
					ContainerRuntime:     ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(MetricConfig{}, ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := DefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				ContainerCommandLine: ResourceAttributeConfig{Enabled: true},
				ContainerHostname:    ResourceAttributeConfig{Enabled: true},
				ContainerID:          ResourceAttributeConfig{Enabled: true},
				ContainerImageID:     ResourceAttributeConfig{Enabled: true},
				ContainerImageName:   ResourceAttributeConfig{Enabled: true},
				ContainerName:        ResourceAttributeConfig{Enabled: true},
				ContainerRuntime:     ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				ContainerCommandLine: ResourceAttributeConfig{Enabled: false},
				ContainerHostname:    ResourceAttributeConfig{Enabled: false},
				ContainerID:          ResourceAttributeConfig{Enabled: false},
				ContainerImageID:     ResourceAttributeConfig{Enabled: false},
				ContainerImageName:   ResourceAttributeConfig{Enabled: false},
				ContainerName:        ResourceAttributeConfig{Enabled: false},
				ContainerRuntime:     ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
